### ISSUE TITLE
The old usernames do not work

### ISSUE THREAD

**Issue by adrianchivu** [RHEAGROUP/COMET-IME-Community-Edition#767]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When creating new users the old OCDT way of working (adding a "."in between first and last name as the username) does not work. the system does not allow a "."to be present in the username. This is also an issue when users need to be modified, the system does not allow the changes to be saved with the old username.

**Comment by samatrhea** [comment]
the regex (and errortext) in the `ValidationService` class will need to be updated , see line 71:

```
{ "PersonShortName", new ValidationRule { PropertyName = "Value", Rule = @"^\w+[\s\w]*$", ErrorText = "The User Name cannot be empty and must contain only alphanumeric characters and spaces." } },
```

**Comment by cozminvelciu** [comment]
According to 10-25, the restrictions for the login username, which is the "shortName" property on the "Person" object, are the following:
* short human readable character string in English that preserves the essential aspects of the name by which something can be referred to
* Note 1: The implied LanguageCode of shortName is "en-GB".
* Note 2: The shortName is meant to be used to refer to something where little space is available, for example to name a domain of expertise, a parameter or a measurement scale or unit in the column header of a table or in a formula.
* Note 3: A shortName may be an acronym or an abbreviated term.
* Note 4: A shortName should not contain any whitespace. Additional constraints are defined for some specializations of ShortNamedThing in order to ensure that the shortName can be used as a variable name in a programming or modelling language.

As a summary, the only restriction defined for "shortName" is that no whitespaces are allowed, as no additional restrictions are defined on the specialization of ShortNamedThing.

**Comment by cozminvelciu** [comment]
Note that it seems that there is no server-side validation for the username.
