### ISSUE TITLE
Rebuilding the datasource in the reporting tool forces the user to put in any manual values again.

### ISSUE THREAD

**Issue by JVennekens** [RHEAGROUP/COMET-IME-Community-Edition#806]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the COMET-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I want to rebuild the datasource in the reporting tool I have to go back to the designer window, This forces me to again put in all values I had to put in the preview tab of my reports. As a user I prefer I did not need to go back to the designer window and I can rebuild the datasource from the preview tab.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
Unfortunately, the proposed solution is not possible due to the flow the reporting plugin has to follow.
If you want reporting parameters to be persisted, you should use the parameter editor in the report designer:


Rightclick on the Parameters row in the Field List tab and choose "Edit Parameters".
![image](https://user-images.githubusercontent.com/56023674/118479066-dc668c80-b710-11eb-9a9c-848b103e4378.png)

Find the parameter you want to persist the changed value and change its "Default Value" to the value you wish.
![image](https://user-images.githubusercontent.com/56023674/118479361-38c9ac00-b711-11eb-8111-e39841389bc9.png)

Press OK and save the report file.

The value will be persisted within the report file (reportname.rep4). You can still (temporarily) change it in the report previewer.

**Comment by lxatrhea** [comment]
By chance I found a way to do this. Apparently we can re-submit parameters. So a rebuild followed by a programmatic re-submission of parameters will work.

Only thing that might not be possible is refreshing the Parameters panel. In theory a new report parameter could be created during Rebuild and that new report parameter probably won't be added to the Parameter panel.
