### ISSUE TITLE
As a user I want to see in the details panel of the ElementDefinitionBrowser in which option an ElementUsage is included/excluded

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#998]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
As a user I want to see in the details panel of the ElementDefinitionBrowser in which option an ElementUsage is included/excluded

### Steps to Reproduce

- Open browser
- open details view (bottom of the browser)
- select an ElementUsage in see that the option information is not yet included here

 -> implementation requires update of tooltipservice

 
### System Configuration

- COMET version:
  - [x] COMET-IME:  9.0.x

**Comment by MartinFijneman** [comment]
tested with 9.4.0 RC2

reopen, small fix required:

2x "exclude" is text instead of correct overview of:
excluded options
_**included**_ options

note: it is just the typo in the bottom label text itself (see screenshot, in red), the selection of excluded and included options are given correctly.

![image](https://user-images.githubusercontent.com/35371313/223446321-cc28eadc-7070-41c3-b8f5-8490c71ef661.png)
